//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JZJW.Winder.BLL.wsf {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Iservice.cxf.tsinghua.com/", ConfigurationName="wsf.GlobalForcastRainDataInfo")]
    public interface GlobalForcastRainDataInfo {
        
        // CODEGEN: 命名空间  的元素名称 return 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JZJW.Winder.BLL.wsf.GetUnParseForcastDataResponse GetUnParseForcastData(JZJW.Winder.BLL.wsf.GetUnParseForcastData request);
        
        // CODEGEN: 命名空间  的元素名称 arg2 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JZJW.Winder.BLL.wsf.QueryForcastRainDataByLocationResponse QueryForcastRainDataByLocation(JZJW.Winder.BLL.wsf.QueryForcastRainDataByLocation request);
        
        // CODEGEN: 命名空间  的元素名称 arg4 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JZJW.Winder.BLL.wsf.QueryForcastRainDataByRangeResponse QueryForcastRainDataByRange(JZJW.Winder.BLL.wsf.QueryForcastRainDataByRange request);
        
        // CODEGEN: 命名空间  的元素名称 return 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JZJW.Winder.BLL.wsf.OrganizationInfoResponse OrganizationInfo(JZJW.Winder.BLL.wsf.OrganizationInfo request);
        
        // CODEGEN: 命名空间  的元素名称 return 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JZJW.Winder.BLL.wsf.QueryLocationResponse QueryLocation(JZJW.Winder.BLL.wsf.QueryLocation request);
        
        // CODEGEN: 命名空间  的元素名称 arg2 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JZJW.Winder.BLL.wsf.GetForcastRainDataResponse GetForcastRainData(JZJW.Winder.BLL.wsf.GetForcastRainData request);
        
        // CODEGEN: 命名空间  的元素名称 return 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JZJW.Winder.BLL.wsf.ObtainFactorInfoResponse ObtainFactorInfo(JZJW.Winder.BLL.wsf.ObtainFactorInfo request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JZJW.Winder.BLL.wsf.ObtainFactorsResponse ObtainFactors(JZJW.Winder.BLL.wsf.ObtainFactors request);
        
        // CODEGEN: 命名空间  的元素名称 arg2 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JZJW.Winder.BLL.wsf.QueryForcastRainDataResponse QueryForcastRainData(JZJW.Winder.BLL.wsf.QueryForcastRainData request);
        
        // CODEGEN: 命名空间  的元素名称 return 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JZJW.Winder.BLL.wsf.ObtainForcastRainDataResponse ObtainForcastRainData(JZJW.Winder.BLL.wsf.ObtainForcastRainData request);
        
        // CODEGEN: 命名空间  的元素名称 return 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JZJW.Winder.BLL.wsf.QueryPointsInRangeResponse QueryPointsInRange(JZJW.Winder.BLL.wsf.QueryPointsInRange request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUnParseForcastData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnParseForcastData", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.GetUnParseForcastDataBody Body;
        
        public GetUnParseForcastData() {
        }
        
        public GetUnParseForcastData(JZJW.Winder.BLL.wsf.GetUnParseForcastDataBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUnParseForcastDataBody {
        
        public GetUnParseForcastDataBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUnParseForcastDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnParseForcastDataResponse", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.GetUnParseForcastDataResponseBody Body;
        
        public GetUnParseForcastDataResponse() {
        }
        
        public GetUnParseForcastDataResponse(JZJW.Winder.BLL.wsf.GetUnParseForcastDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetUnParseForcastDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetUnParseForcastDataResponseBody() {
        }
        
        public GetUnParseForcastDataResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryForcastRainDataByLocation {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryForcastRainDataByLocation", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.QueryForcastRainDataByLocationBody Body;
        
        public QueryForcastRainDataByLocation() {
        }
        
        public QueryForcastRainDataByLocation(JZJW.Winder.BLL.wsf.QueryForcastRainDataByLocationBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryForcastRainDataByLocationBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string arg5;
        
        public QueryForcastRainDataByLocationBody() {
        }
        
        public QueryForcastRainDataByLocationBody(double arg0, double arg1, string arg2, int arg3, string arg4, string arg5) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryForcastRainDataByLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryForcastRainDataByLocationResponse", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.QueryForcastRainDataByLocationResponseBody Body;
        
        public QueryForcastRainDataByLocationResponse() {
        }
        
        public QueryForcastRainDataByLocationResponse(JZJW.Winder.BLL.wsf.QueryForcastRainDataByLocationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryForcastRainDataByLocationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public QueryForcastRainDataByLocationResponseBody() {
        }
        
        public QueryForcastRainDataByLocationResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryForcastRainDataByRange {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryForcastRainDataByRange", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.QueryForcastRainDataByRangeBody Body;
        
        public QueryForcastRainDataByRange() {
        }
        
        public QueryForcastRainDataByRange(JZJW.Winder.BLL.wsf.QueryForcastRainDataByRangeBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryForcastRainDataByRangeBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string arg5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string arg6;
        
        public QueryForcastRainDataByRangeBody() {
        }
        
        public QueryForcastRainDataByRangeBody(double arg0, double arg1, double arg2, double arg3, string arg4, string arg5, string arg6) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryForcastRainDataByRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryForcastRainDataByRangeResponse", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.QueryForcastRainDataByRangeResponseBody Body;
        
        public QueryForcastRainDataByRangeResponse() {
        }
        
        public QueryForcastRainDataByRangeResponse(JZJW.Winder.BLL.wsf.QueryForcastRainDataByRangeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryForcastRainDataByRangeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public QueryForcastRainDataByRangeResponseBody() {
        }
        
        public QueryForcastRainDataByRangeResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrganizationInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrganizationInfo", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.OrganizationInfoBody Body;
        
        public OrganizationInfo() {
        }
        
        public OrganizationInfo(JZJW.Winder.BLL.wsf.OrganizationInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class OrganizationInfoBody {
        
        public OrganizationInfoBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrganizationInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrganizationInfoResponse", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.OrganizationInfoResponseBody Body;
        
        public OrganizationInfoResponse() {
        }
        
        public OrganizationInfoResponse(JZJW.Winder.BLL.wsf.OrganizationInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class OrganizationInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public OrganizationInfoResponseBody() {
        }
        
        public OrganizationInfoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryLocation {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryLocation", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.QueryLocationBody Body;
        
        public QueryLocation() {
        }
        
        public QueryLocation(JZJW.Winder.BLL.wsf.QueryLocationBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryLocationBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long arg1;
        
        public QueryLocationBody() {
        }
        
        public QueryLocationBody(long arg0, long arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryLocationResponse", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.QueryLocationResponseBody Body;
        
        public QueryLocationResponse() {
        }
        
        public QueryLocationResponse(JZJW.Winder.BLL.wsf.QueryLocationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryLocationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public QueryLocationResponseBody() {
        }
        
        public QueryLocationResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetForcastRainData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetForcastRainData", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.GetForcastRainDataBody Body;
        
        public GetForcastRainData() {
        }
        
        public GetForcastRainData(JZJW.Winder.BLL.wsf.GetForcastRainDataBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetForcastRainDataBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        public GetForcastRainDataBody() {
        }
        
        public GetForcastRainDataBody(double arg0, double arg1, string arg2, string arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetForcastRainDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetForcastRainDataResponse", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.GetForcastRainDataResponseBody Body;
        
        public GetForcastRainDataResponse() {
        }
        
        public GetForcastRainDataResponse(JZJW.Winder.BLL.wsf.GetForcastRainDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetForcastRainDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetForcastRainDataResponseBody() {
        }
        
        public GetForcastRainDataResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtainFactorInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtainFactorInfo", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.ObtainFactorInfoBody Body;
        
        public ObtainFactorInfo() {
        }
        
        public ObtainFactorInfo(JZJW.Winder.BLL.wsf.ObtainFactorInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtainFactorInfoBody {
        
        public ObtainFactorInfoBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtainFactorInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtainFactorInfoResponse", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.ObtainFactorInfoResponseBody Body;
        
        public ObtainFactorInfoResponse() {
        }
        
        public ObtainFactorInfoResponse(JZJW.Winder.BLL.wsf.ObtainFactorInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ObtainFactorInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ObtainFactorInfoResponseBody() {
        }
        
        public ObtainFactorInfoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtainFactors {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtainFactors", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.ObtainFactorsBody Body;
        
        public ObtainFactors() {
        }
        
        public ObtainFactors(JZJW.Winder.BLL.wsf.ObtainFactorsBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ObtainFactorsBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public ObtainFactorsBody() {
        }
        
        public ObtainFactorsBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtainFactorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtainFactorsResponse", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.ObtainFactorsResponseBody Body;
        
        public ObtainFactorsResponse() {
        }
        
        public ObtainFactorsResponse(JZJW.Winder.BLL.wsf.ObtainFactorsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ObtainFactorsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ObtainFactorsResponseBody() {
        }
        
        public ObtainFactorsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryForcastRainData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryForcastRainData", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.QueryForcastRainDataBody Body;
        
        public QueryForcastRainData() {
        }
        
        public QueryForcastRainData(JZJW.Winder.BLL.wsf.QueryForcastRainDataBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryForcastRainDataBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        public QueryForcastRainDataBody() {
        }
        
        public QueryForcastRainDataBody(double arg0, double arg1, string arg2, string arg3, string arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryForcastRainDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryForcastRainDataResponse", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.QueryForcastRainDataResponseBody Body;
        
        public QueryForcastRainDataResponse() {
        }
        
        public QueryForcastRainDataResponse(JZJW.Winder.BLL.wsf.QueryForcastRainDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryForcastRainDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public QueryForcastRainDataResponseBody() {
        }
        
        public QueryForcastRainDataResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtainForcastRainData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtainForcastRainData", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.ObtainForcastRainDataBody Body;
        
        public ObtainForcastRainData() {
        }
        
        public ObtainForcastRainData(JZJW.Winder.BLL.wsf.ObtainForcastRainDataBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtainForcastRainDataBody {
        
        public ObtainForcastRainDataBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtainForcastRainDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtainForcastRainDataResponse", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.ObtainForcastRainDataResponseBody Body;
        
        public ObtainForcastRainDataResponse() {
        }
        
        public ObtainForcastRainDataResponse(JZJW.Winder.BLL.wsf.ObtainForcastRainDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ObtainForcastRainDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ObtainForcastRainDataResponseBody() {
        }
        
        public ObtainForcastRainDataResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryPointsInRange {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryPointsInRange", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.QueryPointsInRangeBody Body;
        
        public QueryPointsInRange() {
        }
        
        public QueryPointsInRange(JZJW.Winder.BLL.wsf.QueryPointsInRangeBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryPointsInRangeBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double arg4;
        
        public QueryPointsInRangeBody() {
        }
        
        public QueryPointsInRangeBody(double arg0, double arg1, double arg2, double arg3, double arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryPointsInRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryPointsInRangeResponse", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf.QueryPointsInRangeResponseBody Body;
        
        public QueryPointsInRangeResponse() {
        }
        
        public QueryPointsInRangeResponse(JZJW.Winder.BLL.wsf.QueryPointsInRangeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryPointsInRangeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public QueryPointsInRangeResponseBody() {
        }
        
        public QueryPointsInRangeResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GlobalForcastRainDataInfoChannel : JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GlobalForcastRainDataInfoClient : System.ServiceModel.ClientBase<JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo>, JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo {
        
        public GlobalForcastRainDataInfoClient() {
        }
        
        public GlobalForcastRainDataInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GlobalForcastRainDataInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlobalForcastRainDataInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlobalForcastRainDataInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JZJW.Winder.BLL.wsf.GetUnParseForcastDataResponse JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo.GetUnParseForcastData(JZJW.Winder.BLL.wsf.GetUnParseForcastData request) {
            return base.Channel.GetUnParseForcastData(request);
        }
        
        public string GetUnParseForcastData() {
            JZJW.Winder.BLL.wsf.GetUnParseForcastData inValue = new JZJW.Winder.BLL.wsf.GetUnParseForcastData();
            inValue.Body = new JZJW.Winder.BLL.wsf.GetUnParseForcastDataBody();
            JZJW.Winder.BLL.wsf.GetUnParseForcastDataResponse retVal = ((JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo)(this)).GetUnParseForcastData(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JZJW.Winder.BLL.wsf.QueryForcastRainDataByLocationResponse JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo.QueryForcastRainDataByLocation(JZJW.Winder.BLL.wsf.QueryForcastRainDataByLocation request) {
            return base.Channel.QueryForcastRainDataByLocation(request);
        }
        
        public string QueryForcastRainDataByLocation(double arg0, double arg1, string arg2, int arg3, string arg4, string arg5) {
            JZJW.Winder.BLL.wsf.QueryForcastRainDataByLocation inValue = new JZJW.Winder.BLL.wsf.QueryForcastRainDataByLocation();
            inValue.Body = new JZJW.Winder.BLL.wsf.QueryForcastRainDataByLocationBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            JZJW.Winder.BLL.wsf.QueryForcastRainDataByLocationResponse retVal = ((JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo)(this)).QueryForcastRainDataByLocation(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JZJW.Winder.BLL.wsf.QueryForcastRainDataByRangeResponse JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo.QueryForcastRainDataByRange(JZJW.Winder.BLL.wsf.QueryForcastRainDataByRange request) {
            return base.Channel.QueryForcastRainDataByRange(request);
        }
        
        public string QueryForcastRainDataByRange(double arg0, double arg1, double arg2, double arg3, string arg4, string arg5, string arg6) {
            JZJW.Winder.BLL.wsf.QueryForcastRainDataByRange inValue = new JZJW.Winder.BLL.wsf.QueryForcastRainDataByRange();
            inValue.Body = new JZJW.Winder.BLL.wsf.QueryForcastRainDataByRangeBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            JZJW.Winder.BLL.wsf.QueryForcastRainDataByRangeResponse retVal = ((JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo)(this)).QueryForcastRainDataByRange(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JZJW.Winder.BLL.wsf.OrganizationInfoResponse JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo.OrganizationInfo(JZJW.Winder.BLL.wsf.OrganizationInfo request) {
            return base.Channel.OrganizationInfo(request);
        }
        
        public string OrganizationInfo() {
            JZJW.Winder.BLL.wsf.OrganizationInfo inValue = new JZJW.Winder.BLL.wsf.OrganizationInfo();
            inValue.Body = new JZJW.Winder.BLL.wsf.OrganizationInfoBody();
            JZJW.Winder.BLL.wsf.OrganizationInfoResponse retVal = ((JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo)(this)).OrganizationInfo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JZJW.Winder.BLL.wsf.QueryLocationResponse JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo.QueryLocation(JZJW.Winder.BLL.wsf.QueryLocation request) {
            return base.Channel.QueryLocation(request);
        }
        
        public string QueryLocation(long arg0, long arg1) {
            JZJW.Winder.BLL.wsf.QueryLocation inValue = new JZJW.Winder.BLL.wsf.QueryLocation();
            inValue.Body = new JZJW.Winder.BLL.wsf.QueryLocationBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            JZJW.Winder.BLL.wsf.QueryLocationResponse retVal = ((JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo)(this)).QueryLocation(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JZJW.Winder.BLL.wsf.GetForcastRainDataResponse JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo.GetForcastRainData(JZJW.Winder.BLL.wsf.GetForcastRainData request) {
            return base.Channel.GetForcastRainData(request);
        }
        
        public string GetForcastRainData(double arg0, double arg1, string arg2, string arg3) {
            JZJW.Winder.BLL.wsf.GetForcastRainData inValue = new JZJW.Winder.BLL.wsf.GetForcastRainData();
            inValue.Body = new JZJW.Winder.BLL.wsf.GetForcastRainDataBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            JZJW.Winder.BLL.wsf.GetForcastRainDataResponse retVal = ((JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo)(this)).GetForcastRainData(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JZJW.Winder.BLL.wsf.ObtainFactorInfoResponse JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo.ObtainFactorInfo(JZJW.Winder.BLL.wsf.ObtainFactorInfo request) {
            return base.Channel.ObtainFactorInfo(request);
        }
        
        public string ObtainFactorInfo() {
            JZJW.Winder.BLL.wsf.ObtainFactorInfo inValue = new JZJW.Winder.BLL.wsf.ObtainFactorInfo();
            inValue.Body = new JZJW.Winder.BLL.wsf.ObtainFactorInfoBody();
            JZJW.Winder.BLL.wsf.ObtainFactorInfoResponse retVal = ((JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo)(this)).ObtainFactorInfo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JZJW.Winder.BLL.wsf.ObtainFactorsResponse JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo.ObtainFactors(JZJW.Winder.BLL.wsf.ObtainFactors request) {
            return base.Channel.ObtainFactors(request);
        }
        
        public string ObtainFactors(string arg0, string arg1) {
            JZJW.Winder.BLL.wsf.ObtainFactors inValue = new JZJW.Winder.BLL.wsf.ObtainFactors();
            inValue.Body = new JZJW.Winder.BLL.wsf.ObtainFactorsBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            JZJW.Winder.BLL.wsf.ObtainFactorsResponse retVal = ((JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo)(this)).ObtainFactors(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JZJW.Winder.BLL.wsf.QueryForcastRainDataResponse JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo.QueryForcastRainData(JZJW.Winder.BLL.wsf.QueryForcastRainData request) {
            return base.Channel.QueryForcastRainData(request);
        }
        
        public string QueryForcastRainData(double arg0, double arg1, string arg2, string arg3, string arg4) {
            JZJW.Winder.BLL.wsf.QueryForcastRainData inValue = new JZJW.Winder.BLL.wsf.QueryForcastRainData();
            inValue.Body = new JZJW.Winder.BLL.wsf.QueryForcastRainDataBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            JZJW.Winder.BLL.wsf.QueryForcastRainDataResponse retVal = ((JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo)(this)).QueryForcastRainData(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JZJW.Winder.BLL.wsf.ObtainForcastRainDataResponse JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo.ObtainForcastRainData(JZJW.Winder.BLL.wsf.ObtainForcastRainData request) {
            return base.Channel.ObtainForcastRainData(request);
        }
        
        public string ObtainForcastRainData() {
            JZJW.Winder.BLL.wsf.ObtainForcastRainData inValue = new JZJW.Winder.BLL.wsf.ObtainForcastRainData();
            inValue.Body = new JZJW.Winder.BLL.wsf.ObtainForcastRainDataBody();
            JZJW.Winder.BLL.wsf.ObtainForcastRainDataResponse retVal = ((JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo)(this)).ObtainForcastRainData(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JZJW.Winder.BLL.wsf.QueryPointsInRangeResponse JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo.QueryPointsInRange(JZJW.Winder.BLL.wsf.QueryPointsInRange request) {
            return base.Channel.QueryPointsInRange(request);
        }
        
        public string QueryPointsInRange(double arg0, double arg1, double arg2, double arg3, double arg4) {
            JZJW.Winder.BLL.wsf.QueryPointsInRange inValue = new JZJW.Winder.BLL.wsf.QueryPointsInRange();
            inValue.Body = new JZJW.Winder.BLL.wsf.QueryPointsInRangeBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            JZJW.Winder.BLL.wsf.QueryPointsInRangeResponse retVal = ((JZJW.Winder.BLL.wsf.GlobalForcastRainDataInfo)(this)).QueryPointsInRange(inValue);
            return retVal.Body.@return;
        }
    }
}
