//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JZJW.Winder.BLL.wsf2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Iservice.cxf.tsinghua.com/", ConfigurationName="wsf2.GlobalForcastRainDataServer")]
    public interface GlobalForcastRainDataServer {
        
        // CODEGEN: 命名空间  的元素名称 arg4 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JZJW.Winder.BLL.wsf2.QueryLatestForcastRainDataByRangeResponse QueryLatestForcastRainDataByRange(JZJW.Winder.BLL.wsf2.QueryLatestForcastRainDataByRange request);
        
        // CODEGEN: 命名空间  的元素名称 arg4 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JZJW.Winder.BLL.wsf2.QueryForcastRainDataByRangeResponse QueryForcastRainDataByRange(JZJW.Winder.BLL.wsf2.QueryForcastRainDataByRange request);
        
        // CODEGEN: 命名空间  的元素名称 arg4 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JZJW.Winder.BLL.wsf2.QueryHistoryForcastDataResponse QueryHistoryForcastData(JZJW.Winder.BLL.wsf2.QueryHistoryForcastData request);
        
        // CODEGEN: 命名空间  的元素名称 return 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JZJW.Winder.BLL.wsf2.ObtainLatestForcastDateResponse ObtainLatestForcastDate(JZJW.Winder.BLL.wsf2.ObtainLatestForcastDate request);
        
        // CODEGEN: 命名空间  的元素名称 arg2 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JZJW.Winder.BLL.wsf2.QueryForcastRainDataResponse QueryForcastRainData(JZJW.Winder.BLL.wsf2.QueryForcastRainData request);
        
        // CODEGEN: 命名空间  的元素名称 return 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JZJW.Winder.BLL.wsf2.QueryPointsInRangeResponse QueryPointsInRange(JZJW.Winder.BLL.wsf2.QueryPointsInRange request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryLatestForcastRainDataByRange {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryLatestForcastRainDataByRange", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf2.QueryLatestForcastRainDataByRangeBody Body;
        
        public QueryLatestForcastRainDataByRange() {
        }
        
        public QueryLatestForcastRainDataByRange(JZJW.Winder.BLL.wsf2.QueryLatestForcastRainDataByRangeBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryLatestForcastRainDataByRangeBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string arg5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string arg6;
        
        public QueryLatestForcastRainDataByRangeBody() {
        }
        
        public QueryLatestForcastRainDataByRangeBody(double arg0, double arg1, double arg2, double arg3, string arg4, string arg5, string arg6) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryLatestForcastRainDataByRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryLatestForcastRainDataByRangeResponse", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf2.QueryLatestForcastRainDataByRangeResponseBody Body;
        
        public QueryLatestForcastRainDataByRangeResponse() {
        }
        
        public QueryLatestForcastRainDataByRangeResponse(JZJW.Winder.BLL.wsf2.QueryLatestForcastRainDataByRangeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryLatestForcastRainDataByRangeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public QueryLatestForcastRainDataByRangeResponseBody() {
        }
        
        public QueryLatestForcastRainDataByRangeResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryForcastRainDataByRange {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryForcastRainDataByRange", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf2.QueryForcastRainDataByRangeBody Body;
        
        public QueryForcastRainDataByRange() {
        }
        
        public QueryForcastRainDataByRange(JZJW.Winder.BLL.wsf2.QueryForcastRainDataByRangeBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryForcastRainDataByRangeBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string arg5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string arg6;
        
        public QueryForcastRainDataByRangeBody() {
        }
        
        public QueryForcastRainDataByRangeBody(double arg0, double arg1, double arg2, double arg3, string arg4, string arg5, string arg6) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryForcastRainDataByRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryForcastRainDataByRangeResponse", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf2.QueryForcastRainDataByRangeResponseBody Body;
        
        public QueryForcastRainDataByRangeResponse() {
        }
        
        public QueryForcastRainDataByRangeResponse(JZJW.Winder.BLL.wsf2.QueryForcastRainDataByRangeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryForcastRainDataByRangeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public QueryForcastRainDataByRangeResponseBody() {
        }
        
        public QueryForcastRainDataByRangeResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryHistoryForcastData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryHistoryForcastData", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf2.QueryHistoryForcastDataBody Body;
        
        public QueryHistoryForcastData() {
        }
        
        public QueryHistoryForcastData(JZJW.Winder.BLL.wsf2.QueryHistoryForcastDataBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryHistoryForcastDataBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string arg5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string arg6;
        
        public QueryHistoryForcastDataBody() {
        }
        
        public QueryHistoryForcastDataBody(double arg0, double arg1, double arg2, double arg3, string arg4, string arg5, string arg6) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryHistoryForcastDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryHistoryForcastDataResponse", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf2.QueryHistoryForcastDataResponseBody Body;
        
        public QueryHistoryForcastDataResponse() {
        }
        
        public QueryHistoryForcastDataResponse(JZJW.Winder.BLL.wsf2.QueryHistoryForcastDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryHistoryForcastDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public QueryHistoryForcastDataResponseBody() {
        }
        
        public QueryHistoryForcastDataResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtainLatestForcastDate {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtainLatestForcastDate", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf2.ObtainLatestForcastDateBody Body;
        
        public ObtainLatestForcastDate() {
        }
        
        public ObtainLatestForcastDate(JZJW.Winder.BLL.wsf2.ObtainLatestForcastDateBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtainLatestForcastDateBody {
        
        public ObtainLatestForcastDateBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtainLatestForcastDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtainLatestForcastDateResponse", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf2.ObtainLatestForcastDateResponseBody Body;
        
        public ObtainLatestForcastDateResponse() {
        }
        
        public ObtainLatestForcastDateResponse(JZJW.Winder.BLL.wsf2.ObtainLatestForcastDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ObtainLatestForcastDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ObtainLatestForcastDateResponseBody() {
        }
        
        public ObtainLatestForcastDateResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryForcastRainData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryForcastRainData", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf2.QueryForcastRainDataBody Body;
        
        public QueryForcastRainData() {
        }
        
        public QueryForcastRainData(JZJW.Winder.BLL.wsf2.QueryForcastRainDataBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryForcastRainDataBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        public QueryForcastRainDataBody() {
        }
        
        public QueryForcastRainDataBody(double arg0, double arg1, string arg2, string arg3, string arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryForcastRainDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryForcastRainDataResponse", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf2.QueryForcastRainDataResponseBody Body;
        
        public QueryForcastRainDataResponse() {
        }
        
        public QueryForcastRainDataResponse(JZJW.Winder.BLL.wsf2.QueryForcastRainDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryForcastRainDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public QueryForcastRainDataResponseBody() {
        }
        
        public QueryForcastRainDataResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryPointsInRange {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryPointsInRange", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf2.QueryPointsInRangeBody Body;
        
        public QueryPointsInRange() {
        }
        
        public QueryPointsInRange(JZJW.Winder.BLL.wsf2.QueryPointsInRangeBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryPointsInRangeBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double arg4;
        
        public QueryPointsInRangeBody() {
        }
        
        public QueryPointsInRangeBody(double arg0, double arg1, double arg2, double arg3, double arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryPointsInRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryPointsInRangeResponse", Namespace="http://Iservice.cxf.tsinghua.com/", Order=0)]
        public JZJW.Winder.BLL.wsf2.QueryPointsInRangeResponseBody Body;
        
        public QueryPointsInRangeResponse() {
        }
        
        public QueryPointsInRangeResponse(JZJW.Winder.BLL.wsf2.QueryPointsInRangeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class QueryPointsInRangeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public QueryPointsInRangeResponseBody() {
        }
        
        public QueryPointsInRangeResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GlobalForcastRainDataServerChannel : JZJW.Winder.BLL.wsf2.GlobalForcastRainDataServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GlobalForcastRainDataServerClient : System.ServiceModel.ClientBase<JZJW.Winder.BLL.wsf2.GlobalForcastRainDataServer>, JZJW.Winder.BLL.wsf2.GlobalForcastRainDataServer {
        
        public GlobalForcastRainDataServerClient() {
        }
        
        public GlobalForcastRainDataServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GlobalForcastRainDataServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlobalForcastRainDataServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlobalForcastRainDataServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JZJW.Winder.BLL.wsf2.QueryLatestForcastRainDataByRangeResponse JZJW.Winder.BLL.wsf2.GlobalForcastRainDataServer.QueryLatestForcastRainDataByRange(JZJW.Winder.BLL.wsf2.QueryLatestForcastRainDataByRange request) {
            return base.Channel.QueryLatestForcastRainDataByRange(request);
        }
        
        public string QueryLatestForcastRainDataByRange(double arg0, double arg1, double arg2, double arg3, string arg4, string arg5, string arg6) {
            JZJW.Winder.BLL.wsf2.QueryLatestForcastRainDataByRange inValue = new JZJW.Winder.BLL.wsf2.QueryLatestForcastRainDataByRange();
            inValue.Body = new JZJW.Winder.BLL.wsf2.QueryLatestForcastRainDataByRangeBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            JZJW.Winder.BLL.wsf2.QueryLatestForcastRainDataByRangeResponse retVal = ((JZJW.Winder.BLL.wsf2.GlobalForcastRainDataServer)(this)).QueryLatestForcastRainDataByRange(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JZJW.Winder.BLL.wsf2.QueryForcastRainDataByRangeResponse JZJW.Winder.BLL.wsf2.GlobalForcastRainDataServer.QueryForcastRainDataByRange(JZJW.Winder.BLL.wsf2.QueryForcastRainDataByRange request) {
            return base.Channel.QueryForcastRainDataByRange(request);
        }
        
        public string QueryForcastRainDataByRange(double arg0, double arg1, double arg2, double arg3, string arg4, string arg5, string arg6) {
            JZJW.Winder.BLL.wsf2.QueryForcastRainDataByRange inValue = new JZJW.Winder.BLL.wsf2.QueryForcastRainDataByRange();
            inValue.Body = new JZJW.Winder.BLL.wsf2.QueryForcastRainDataByRangeBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            JZJW.Winder.BLL.wsf2.QueryForcastRainDataByRangeResponse retVal = ((JZJW.Winder.BLL.wsf2.GlobalForcastRainDataServer)(this)).QueryForcastRainDataByRange(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JZJW.Winder.BLL.wsf2.QueryHistoryForcastDataResponse JZJW.Winder.BLL.wsf2.GlobalForcastRainDataServer.QueryHistoryForcastData(JZJW.Winder.BLL.wsf2.QueryHistoryForcastData request) {
            return base.Channel.QueryHistoryForcastData(request);
        }
        
        public string QueryHistoryForcastData(double arg0, double arg1, double arg2, double arg3, string arg4, string arg5, string arg6) {
            JZJW.Winder.BLL.wsf2.QueryHistoryForcastData inValue = new JZJW.Winder.BLL.wsf2.QueryHistoryForcastData();
            inValue.Body = new JZJW.Winder.BLL.wsf2.QueryHistoryForcastDataBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            JZJW.Winder.BLL.wsf2.QueryHistoryForcastDataResponse retVal = ((JZJW.Winder.BLL.wsf2.GlobalForcastRainDataServer)(this)).QueryHistoryForcastData(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JZJW.Winder.BLL.wsf2.ObtainLatestForcastDateResponse JZJW.Winder.BLL.wsf2.GlobalForcastRainDataServer.ObtainLatestForcastDate(JZJW.Winder.BLL.wsf2.ObtainLatestForcastDate request) {
            return base.Channel.ObtainLatestForcastDate(request);
        }
        
        public string ObtainLatestForcastDate() {
            JZJW.Winder.BLL.wsf2.ObtainLatestForcastDate inValue = new JZJW.Winder.BLL.wsf2.ObtainLatestForcastDate();
            inValue.Body = new JZJW.Winder.BLL.wsf2.ObtainLatestForcastDateBody();
            JZJW.Winder.BLL.wsf2.ObtainLatestForcastDateResponse retVal = ((JZJW.Winder.BLL.wsf2.GlobalForcastRainDataServer)(this)).ObtainLatestForcastDate(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JZJW.Winder.BLL.wsf2.QueryForcastRainDataResponse JZJW.Winder.BLL.wsf2.GlobalForcastRainDataServer.QueryForcastRainData(JZJW.Winder.BLL.wsf2.QueryForcastRainData request) {
            return base.Channel.QueryForcastRainData(request);
        }
        
        public string QueryForcastRainData(double arg0, double arg1, string arg2, string arg3, string arg4) {
            JZJW.Winder.BLL.wsf2.QueryForcastRainData inValue = new JZJW.Winder.BLL.wsf2.QueryForcastRainData();
            inValue.Body = new JZJW.Winder.BLL.wsf2.QueryForcastRainDataBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            JZJW.Winder.BLL.wsf2.QueryForcastRainDataResponse retVal = ((JZJW.Winder.BLL.wsf2.GlobalForcastRainDataServer)(this)).QueryForcastRainData(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JZJW.Winder.BLL.wsf2.QueryPointsInRangeResponse JZJW.Winder.BLL.wsf2.GlobalForcastRainDataServer.QueryPointsInRange(JZJW.Winder.BLL.wsf2.QueryPointsInRange request) {
            return base.Channel.QueryPointsInRange(request);
        }
        
        public string QueryPointsInRange(double arg0, double arg1, double arg2, double arg3, double arg4) {
            JZJW.Winder.BLL.wsf2.QueryPointsInRange inValue = new JZJW.Winder.BLL.wsf2.QueryPointsInRange();
            inValue.Body = new JZJW.Winder.BLL.wsf2.QueryPointsInRangeBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            JZJW.Winder.BLL.wsf2.QueryPointsInRangeResponse retVal = ((JZJW.Winder.BLL.wsf2.GlobalForcastRainDataServer)(this)).QueryPointsInRange(inValue);
            return retVal.Body.@return;
        }
    }
}
